version: '3.8'

services:
  ravenpoint:
      build:
        context: .
        dockerfile: Dockerfile
      ports:
        - "5000:5000"
      volumes:
        - files:/usr/src/project/data/documents
        - data_files:/usr/src/project/static/files
      command: /bin/bash -c "source activate ravenpoint && python3 app.py"
  maildev:
    image: maildev/maildev
    ports:
      - "1080:1080"
      - "1025:1025"
volumes:
#   code:
  files:
  data_files:
  